name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.os }} build
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [windows-latest, macOS-latest]

    steps:
    - name: Install Conan
      uses: getsentry/action-setup-venv@v2.1.0
      with:
        install-cmd: pip install conan

    - name: Conan Profile Detect
      run: |
        conan profile detect --force

    - name: Checkout Commit
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Upload built package binaries
      uses: actions/upload-artifact@v4
      with:
          name: ${{ matrix.os }} binaries
          path: externals/**/*.*
